export const bookMap: { [key: string]: string } = {
  Genesis: "GEN",
  Exodus: "EXOD",
  Leviticus: "LEV",
  "1 Samuel": "1SAM",
  "2 Samuel": "2SAM",
  "1 Kings": "1KGS",
  Psalm: "PS",
  Proverbs: "PROV",
  Isaiah: "ISA",
  Jeremiah: "JER",
  Daniel: "DAN",
  Matthew: "MATT",
  Luke: "LUKE",
  John: "JOHN",
  Acts: "ACTS",
  Romans: "ROM",
  "1 Corinthians": "1COR",
  "2 Corinthians": "2COR",
  Galatians: "GAL",
  Ephesians: "EPH",
  Philippians: "PHIL",
  Colossians: "COL",
  "1 Timothy": "1TIM",
  "2 Timothy": "2TIM",
  Hebrews: "HEB",
  "1 Peter": "1PET",
  "2 Peter": "2PET",
  Revelation: "REV",
};
